import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module'
import { copyFileSync } from 'node:fs'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	outfile: 'main.js',
};

const testVaultPluginDir = 'test-vault/.obsidian/plugins/immich-picker';

// Plugin to copy build output to test vault
const copyToTestVault = {
	name: 'copy-to-test-vault',
	setup(build) {
		build.onEnd(() => {
			try {
				copyFileSync('main.js', `${testVaultPluginDir}/main.js`);
				copyFileSync('manifest.json', `${testVaultPluginDir}/manifest.json`);
				copyFileSync('styles.css', `${testVaultPluginDir}/styles.css`);
			} catch {
				// Test vault may not exist in CI
			}
		});
	}
};

if (prod) {
	await esbuild.build({ ...buildOptions, plugins: [copyToTestVault] });
} else {
	const context = await esbuild.context({ ...buildOptions, plugins: [copyToTestVault] });
	await context.watch();
}
